examples/raylib: adds missing include for signal.h
compilation breaks (gcc 13.3.0 in Ubuntu 24) due to missing header
inclusion:

```
nbnet/examples/raylib/server.c:303:5: warning: implicit declaration of function ‘signal’; did you mean ‘sinhl’? [-Wimplicit-function-declaration]
  303 |     signal(SIGINT, SigintHandler);
      |     ^~~~~~
      |     sinhl
nbnet/examples/raylib/server.c:303:12: error: ‘SIGINT’ undeclared (first use in this function)
  303 |     signal(SIGINT, SigintHandler);
      |            ^~~~~~

```

Signed-off-by: Gabriel dos Santos Sanches <gabrielssanches@proton.me>